### PR TITLE
Use git-am.sh instead of git apply

### PR DESCRIPTION
**Pull request by csagan5**
Other fixes to local variable declarations

I have cleaned up and released the custom `git-am.sh` script I use to apply patches with deletions (I mentioned this in #1).

Feel free to adjust the PR accordingly. I have not tested it but I opened it so that you know about the `git-am.sh` script.

### CODE REVIEW

**Comment by nikolowry** [comment]
@csagan5 appreciate this. I checked this out locally and made a few adjustments so we can run this prior to the next Bromite release.

Unfortunately I'm getting this error:
`git-am.sh: line 881: git-am-helper: command not found`

I'm on Arch Linux and running git `v2.20.1`.  After looking over git's source, it seems like this shell script has been ported to C: https://github.com/git/git/blob/master/builtin/am.c.

I'm not a big fan of shell aliases, so the following is what I do in my dotfiles if I want to extend/add commands to executables (showing my custom Git commands as an example, excuse the verboseness of conditionals -- it's an oldie of mine):

```shell
#!/bin/sh

git () {
    # Not custom command, so pass args to git to handle normally
    if [[ $@ != "discard" ]] \
            && [[ $@ != "purge" ]] \
            && [[ $@ != "visualize" ]] \
            && [[ $@ != "uncommit" ]]; then
        command git "$@"
    fi

    # Uncommit, reset to head but keep file changes to be restaged
    if [[ $@ == "uncommit" ]]; then
        git reset --mixed HEAD~1
    fi

    # Discard any unstaged local changes
    if [[ $@ == "discard" ]]; then
        git checkout -- .
        git clean -df
    fi

    # Purge all local branches that have been deleted from the remote
    if [[ $@ == "purge" ]]; then
        # Fetch all from remote quietly, only print if a new remote is fetched
        git fetch --all -p | awk '{}'

        # Get all stale|removed remote branches
        STALE=$(git branch -vv | grep ": gone]" | grep "origin" \
                | grep -v "\*" | grep -Ev "(master|development|staging)" \
                | sed -e 's/^[ \t]*//' | awk '{ print $1 }')

        echo $STALE | xargs -n 1 git branch -D
    fi

    # Pretty Git Logs
    if [[ $@ == "visualize" ]]; then
        git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset)%n''        %C(white)%s%C(reset) %C(dim white)- %an%C(reset)' --all
    fi
}
```

Do you think it'd be possible to do something like this and then I could just source the shell script?

**Comment by nikolowry** [comment]
My changes are in https://github.com/nikolowry/bromite-builder/tree/csagan5-patch-1

**Comment by nikolowry** [comment]
Also might be worth investigating and implementing the binary patches in https://github.com/kiwibrowser/privacy_patches/blob/master/Add-bottombar-on-screen-part-1.patch

I'm not a patch guru, so I'm unsure whether the options needed to apply the binary patching would need to be conditional to `Remove-Sync-and-Translate-menu.patch` or if it will be ignored by patches that don't need it

**Comment by csagan5** [comment]
> @csagan5 appreciate this. I checked this out locally and made a few adjustments so we can run this prior to the next Bromite release.
> 
> Unfortunately I'm getting this error:
> `git-am.sh: line 881: git-am-helper: command not found`

I forgot to release that other tool that I wrote myself. I will release it as well, but it is written in Go. You could rewrite it in shell or python to avoid the compilation step.

> I'm on Arch Linux and running git `v2.20.1`. After looking over git's source, it seems like this shell script has been ported to C: https://github.com/git/git/blob/master/builtin/am.c.

Yes, that is correct. But we would not want to recompile `git` so I had to use the old `git am` script instead.

> Do you think it'd be possible to do something like this and then I could just source the shell script?

Asking users to source some alias hardly helps with having other people reproduce the builds...aliases are not used during non-interactive builds for example. As you can see we are drifting very far away from the original goals (and that is why I don't dive into builds & supporting builds).

> My changes are in https://github.com/nikolowry/bromite-builder/tree/csagan5-patch-1

Instead of copying the `git-am.sh` script (and other files) the good practice would be to use them from upstream (Bromite repository in this case).

> Also might be worth investigating and implementing the binary patches in https://github.com/kiwibrowser/privacy_patches/blob/master/Add-bottombar-on-screen-part-1.patch

Sorry, not interested to use or maintain that. The modified `git am` I use is just for deletions.

**Comment by nikolowry** [comment]
@csagan5 I meant creating the `Remove-Sync-and-Translate-menu.patch` with the `--binary` option like Kiwi Browser was doing to remove the drawable in that patch.

I just successfully created and applied a binary version of `Remove-Sync-and-Translate-menu.patch` and just pushed it to `master`, https://github.com/nikolowry/bromite-builder/blob/master/patches/Remove-Sync-and-Translate-menu.patch.

Can we close this and use the modified patch instead?  If we continue down this route I'll have to do a decent bit of clean-up work in `fetch-sync`.  After running `fetch-sync` and `prepare` with this earlier, the following `fetch-sync` call errored out with this:
```
src (ERROR)
----------------------------------------
[0:00:00] Started.
[0:03:08] From https://chromium.googlesource.com/chromium/src
[0:03:08]    84026b734855..5040590a8af1  lkgr-android-internal  -> origin/lkgr-android-internal
[0:03:08]    5cc10d6488da..2107bd87a87c  master                 -> origin/master
[0:03:08]    ef646ba96ba7..14de4d603f28  refs/branch-heads/3626 -> branch-heads/3626
_____ src at 71.0.3578.115
----------------------------------------
Error: 1> 
1> ____ src at 71.0.3578.115
1> 
1> Conflict while rebasing this branch.
1> Fix the conflict and run gclient again.
1> See man git-rebase for details.
```

I then ran `git status`, which sent this to stdout:
```
HEAD detached from 71.0.3578.115
You are in the middle of an am session.
  (fix conflicts and then run "git am --continue")
  (use "git am --skip" to skip this patch)
  (use "git am --abort" to restore the original branch)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

    modified:   DEPS

Untracked files:
  (use "git add <file>..." to include in what will be committed)

    net/third_party/quiche/
    third_party/dawn/
    third_party/glfw/
    third_party/nasm/

no changes added to commit (use "git add" and/or "git commit -a")
```

Really want to avoid detecting and aborting am sessions

**Comment by csagan5** [comment]
@nikolowry that aborted git am session is wrong..by itself. It is not expected to be there at all, not sure it's related to using `git am` in general. All calls to `git am` should succeed and builds should not continue if any failed (non-zero exit code).

I apply patches after the sync by the way.

I like your binary patch solution, I think I did not use that for some other failure down the line - but standard should be always better so I accept the PR, thanks!

What is left over from this PR is using Bromite's `patches_list.txt` but I guess you have that covered already.

**Pull request closed without merging**
